/**
 * PartsSource Design System — Style Dictionary Config
 * Style Dictionary v3 + Token Studio DTCG format ($value/$type)
 */

const StyleDictionary = require('style-dictionary');

// ——— DTCG Parser ————————————————————————————————————————————————
// Converts Token Studio $value/$type to SD value/type recursively

function transformDTCG(node, parentType) {
  if (typeof node !== 'object' || node === null) return node;

  if ('$value' in node) {
    var token = { value: node.$value };
    if (node.$type || parentType) token.type = node.$type || parentType;
    if (node.$description) token.comment = node.$description;
    return token;
  }

  var result = {};
  var groupType = node.$type || parentType;
  var keys = Object.keys(node);
  for (var i = 0; i < keys.length; i++) {
    var key = keys[i];
    if (key.charAt(0) === '$') continue;
    if (typeof node[key] === 'object' && node[key] !== null) {
      result[key] = transformDTCG(node[key], groupType);
    }
  }
  return result;
}

StyleDictionary.registerParser({
  pattern: /\.json$/,
  parse: function(args) {
    try {
      return transformDTCG(JSON.parse(args.contents));
    } catch (e) {
      console.error('Parse error:', e.message);
      return {};
    }
  },
});

// ——— Custom transforms ————————————————————————————————————————————

StyleDictionary.registerTransform({
  name: 'ps/font-size-rem',
  type: 'value',
  matcher: function(token) {
    return token.type === 'fontSizes' &&
      typeof token.value === 'string' &&
      token.value.endsWith('px');
  },
  transformer: function(token) {
    return (parseFloat(token.value) / 16) + 'rem';
  },
});

// ——— Transform groups ————————————————————————————————————————————

StyleDictionary.registerTransformGroup({
  name: 'ps/css',
  transforms: ['attribute/cti', 'name/cti/kebab', 'color/css', 'ps/font-size-rem'],
});

StyleDictionary.registerTransformGroup({
  name: 'ps/typescript',
  transforms: ['attribute/cti', 'name/cti/camel', 'color/css'],
});

// ——— Formats ——————————————————————————————————————————————————————

StyleDictionary.registerFormat({
  name: 'ps/css-variables',
  formatter: function(args) {
    var vars = args.dictionary.allTokens
      .map(function(token) { return '  --' + token.name + ': ' + token.value + ';'; })
      .join('\n');
    return ':root {\n' + vars + '\n}\n';
  },
});

StyleDictionary.registerFormat({
  name: 'ps/typescript-tokens',
  formatter: function(args) {
    var entries = args.dictionary.allTokens
      .map(function(token) { return "  '" + token.name + "': " + JSON.stringify(token.value) + ','; })
      .join('\n');
    return '/** Auto-generated by Style Dictionary — DO NOT EDIT */\nexport const tokens = {\n' + entries + '\n} as const;\n\nexport type TokenName = keyof typeof tokens;\n';
  },
});

// ——— Build ————————————————————————————————————————————————————————

var sd = StyleDictionary.extend({
  source: ['tokens/ps-tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'ps/css',
      buildPath: 'src/tokens/',
      files: [{
        destination: 'tokens.css',
        format: 'ps/css-variables',
        filter: function(token) {
          return ['primitive', 'semantic'].includes(token.path[0]);
        },
      }],
    },
    typescript: {
      transformGroup: 'ps/typescript',
      buildPath: 'src/tokens/',
      files: [{
        destination: 'tokens.ts',
        format: 'ps/typescript-tokens',
        filter: function(token) {
          return ['primitive', 'semantic'].includes(token.path[0]);
        },
      }],
    },
  },
});

sd.buildAllPlatforms();
